# ============================================================
# HOMELAB TEMPLATE — FILL IN YOUR VALUES BEFORE DEPLOYING
# ============================================================
{
  # Your Linux username on all cluster nodes
  username = "youruser";

  # Timezone for all nodes (find yours with: timedatectl list-timezones)
  timezone = "Asia/Almaty";

  # SSH public key for passwordless cluster access
  # Generate: ssh-keygen -t ed25519 -C "cluster" -f ~/.ssh/cluster
  clusterSshKey = "ssh-ed25519 REPLACE_WITH_YOUR_PUBLIC_KEY your-email@example.com";

  # ============================================================
  # CLUSTER NODES
  # Each entry maps to a hosts/<hostname>/ directory containing
  # only hardware-configuration.nix (generated by nixos-generate-config).
  # ============================================================
  nodes = {
    # master = {
    #   hostname = "mymaster";  # must match hosts/<hostname>/hardware-configuration.nix
    #   master   = true;
    #   disk     = "/dev/sda";  # verify with: lsblk
    #   tags     = [ "homelab" "master" "mymaster" ];
    # };
    # worker1 = {
    #   hostname = "myworker";
    #   master   = false;
    #   disk     = "/dev/sda";
    #   tags     = [ "homelab" "worker" "myworker" ];
    # };
  };

  # ============================================================
  # DOMAIN & NETWORKING
  # ============================================================

  # Your public domain managed by Cloudflare (used for TLS certs + external DNS)
  domain = "yourdomain.example.com";

  # MetalLB IP pool — must be within your LAN but outside your DHCP range
  metallbPool = "192.168.1.192/26";

  # Specific IPs assigned from the MetalLB pool for each service
  piholeIp    = "192.168.1.250"; # Pi-hole DNS/web UI
  wireguardIp = "192.168.1.194"; # WireGuard VPN endpoint
  nginxIp     = "192.168.1.193"; # Ingress controller

  # Upstream DNS server (usually your router)
  upstreamDns = "192.168.1.1";

  # ============================================================
  # WIREGUARD VPN USERS
  # Generate a keypair per user: wg genkey | tee private.key | wg pubkey > public.key
  # Store public keys in SOPS secrets and reference the secret name here.
  # ============================================================
  wireguardUsers = {
    # "alice" = {
    #   ip              = "10.0.100.2";          # Unique VPN IP per user
    #   group           = "admin";               # "admin" | "family" | "friends" | "guests"
    #   publicKeySecret = "alice_wg_public_key"; # SOPS secret name holding the WG public key
    #   allowedIPs      = "0.0.0.0/0";          # Traffic to route through VPN
    #   nextcloudUser   = "alice";               # Optional: enables Nextcloud VPN-SSO
    #   description     = "Alice — full admin access";
    #   enabled         = true;
    # };
    # "bob" = {
    #   ip              = "10.0.100.3";
    #   group           = "family";
    #   publicKeySecret = "bob_wg_public_key";
    #   allowedIPs      = "192.168.1.0/24";
    #   description     = "Bob — homelab access only";
    #   enabled         = true;
    # };
  };
}
